# -*- mode: python ; coding: utf-8 -*-
import os
import sys


a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.py', '.'),
    ],
    hiddenimports=[
        'discord.gateway',
        'discord.state',
        'discord.http',
        'discord.player',
        'discord.voice_client',
        'discord.channel',
        'discord.guild',
        'discord.message',
        'discord.user',
        'discord.member',
        'discord.role',
        'discord.emoji',
        'discord.reaction',
        'discord.permissions',
        'discord.enums',
        'discord.utils',
        'discord.object',
        'discord.invite',
        'discord.widget',
        'discord.relationship',
        'discord.audit_logs',
        'discord.raw_models',
        'discord.team',
        'discord.sticker',
        'discord.scheduled_event',
        'discord.stage_instance',
        'discord.threads',
        'discord.integrations',
        'discord.interactions',
        'discord.webhook',
        'discord.welcome_screen',
        'discord.embeds',
        'discord.components',
        'discord.colour',
        'discord.flags',
        'discord.errors',
        'discord.enums',
        'discord.backoff',
        'discord.mentions',
        'discord.partial_emoji',
        'discord.file',
        'discord.mixins',
        'discord.voice_state',
        'discord.abc',
        'aiohttp',
        'aiohttp.web',
        'aiohttp.client',
        'aiohttp.connector',
        'aiohttp.helpers',
        'aiohttp.http_parser',
        'aiohttp.streams',
        'aiohttp.multipart',
        'selectolax',
        'selectolax.parser',
        'aiolimiter',
        'multidict',
        'frozenlist',
        'yarl',
        'propcache',
        'charset_normalizer',
        'yaml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'test',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DeadSpaceChecker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
